// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwpfJYnTZi1_xaL3X9ySwtefvdM7FwPNk',
    appId: '1:736572913019:web:3bd7aaac4bc88f4bbbb9de',
    messagingSenderId: '736572913019',
    projectId: 'gmon-50109',
    authDomain: 'gmon-50109.firebaseapp.com',
    storageBucket: 'gmon-50109.firebasestorage.app',
    measurementId: 'G-JXPNCSNKPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-NKnlgtakXlJcDKMNAUda1fhTGbLTZ_A',
    appId: '1:736572913019:android:031fbe0814559ea6bbb9de',
    messagingSenderId: '736572913019',
    projectId: 'gmon-50109',
    storageBucket: 'gmon-50109.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVxKlTCUbbnpA9Oa2zwYFDUo3aOEpuNFo',
    appId: '1:736572913019:ios:5462a1427bf85279bbb9de',
    messagingSenderId: '736572913019',
    projectId: 'gmon-50109',
    storageBucket: 'gmon-50109.firebasestorage.app',
    androidClientId: '736572913019-1a2vhcgud4hh5027cfqmibk9ajm42b4m.apps.googleusercontent.com',
    iosClientId: '736572913019-93pa9rbariob47h3f9sjsvm2fe4036h9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gmon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVxKlTCUbbnpA9Oa2zwYFDUo3aOEpuNFo',
    appId: '1:736572913019:ios:5462a1427bf85279bbb9de',
    messagingSenderId: '736572913019',
    projectId: 'gmon-50109',
    storageBucket: 'gmon-50109.firebasestorage.app',
    androidClientId: '736572913019-1a2vhcgud4hh5027cfqmibk9ajm42b4m.apps.googleusercontent.com',
    iosClientId: '736572913019-93pa9rbariob47h3f9sjsvm2fe4036h9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gmon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwpfJYnTZi1_xaL3X9ySwtefvdM7FwPNk',
    appId: '1:736572913019:web:914ce6c5bb91c806bbb9de',
    messagingSenderId: '736572913019',
    projectId: 'gmon-50109',
    authDomain: 'gmon-50109.firebaseapp.com',
    storageBucket: 'gmon-50109.firebasestorage.app',
    measurementId: 'G-8HFSCXXN3T',
  );
}
